apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  # CRD follow the name <plural-resource-name>.<api-group-name>
  name: "projects.k8s-crd-demo.shawnrong.github.com"
spec:
  group: "k8s-crd-demo.shawnrong.github.com"
  versions:
    - name: "v1alpha1"
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          required: ["spec"]
          type: "object"
          properties:
            spec:
              type: "object"
              required: ["replicas"]
              properties:
                replicas:
                  type: "integer"
                  minimum: 1
  scope: "Namespaced"
  names:
    plural: "projects"
    singular: "project"
    kind: "Project"